### ISSUE TITLE
Empty output in autorefine

### ISSUE THREAD

**Issue by cossorzano** [scipion-em/scipion-em-relion#262]
Using the project that can be downloaded here: http://scipion.cnb.csic.es/downloads/documentation/Example_10248_Scipion3.tgz

The Relion Autorefine (the only one in the project) does not produce any output for the volume or the FSC. If you analyze the results from the last iteration (18), the information is there. But it seems that the output is constructed from the iteration 19, and that one is empty.

Thank you, Carlos Oscar

**Comment by azazellochg** [comment]
Hi @cossorzano thanks for reporting, I'm downloading the project now.

**Comment by azazellochg** [comment]
@cossorzano output is not constructed from the last iteration files (unless you do this in viewer), the problem is with relion and not scipion. It looks like the output volumes are all blank - all pixels are zero. Do you reproduce this error consistently? If yes, you might report this to Relion devs (along with your hardware setup and compilation options). 

I have continued your autorefine with --force-converge option and got a nice 3.44A volume.
