### ISSUE TITLE
regularization parameter tau + continue mode

### ISSUE THREAD

**Issue by pconesa** [scipion-em/scipion-em-relion#28]
From, Jaime (user here at cnb):

He is trying to continue a relion classification from a previous run. he changed the "tau" parameter...but the continuation is not using the new tau value.

**Comment by pconesa** [comment]
and the new value is not persisted.

**Comment by azazellochg** [comment]
relion 2 + scipion 2?

**Comment by pconesa** [comment]
Not sure, we just installed him pluginization but probably is relion2
scipion-1.2.1

I think working in the plugin should be fine.

**Comment by azazellochg** [comment]
I checked, indeed the value from previous protocol is copied (introduced 2y ago, no idea why), affecting all scipion versions. The fix for version 1.2.1 is to comment / delete two lines number 1027 and 1028 (https://github.com/I2PC/scipion/blob/master/pyworkflow/em/packages/relion/protocol_base.py#L1027)

I will fix this in the plugin
